name: Build docs
on:
 push:
  branches:
   - devel
jobs:
  build_docs:
   runs-on: [self-hosted, linux]
   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - run: cd .. && rm -Rf raven && git clone https://github.com/idaholab/raven.git
     - run: python3 ../raven/scripts/install_plugins.py -s TEAL
     - run: python3 ../raven/scripts/install_plugins.py -s ${{ github.workspace }}
     - run: WD=`(cd ../../.. && pwd)` && export RAVEN_LIBS_NAME="raven_libs_"`basename $WD` && ../raven/scripts/establish_conda_env.sh --install
     - run: cd ../raven && ./build_raven
     - name: Build documentation
       run: |
        cd ../raven
        source ./scripts/establish_conda_env.sh --load
        cd ../HERON
        ./doc/make_docs.sh
     - name: Archive documents
       uses: actions/upload-artifact@v3
       with:
         name: pdfs
         path: |
          doc/pdfs
          doc/sqa/sqa_built_documents
     - run: update_heron_docs.sh doc/pdfs/*.pdf doc/sqa/sqa_built_documents/*.pdf
